// <auto-generated />
using System;
using FinanceManager.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManager.Persistence.Migrations
{
    [DbContext(typeof(FinanceManagerContext))]
    [Migration("20210605162714_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccauntSum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.BudgetDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 13, 999, DateTimeKind.Local).AddTicks(3918),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(3377),
                            Name = "Автомобиль",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4124),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4129),
                            Name = "Регулярные платежи",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4136),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4137),
                            Name = "Развлечения",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4141),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4142),
                            Name = "Медицина",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4145),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4146),
                            Name = "Продукты питания",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4154),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4155),
                            Name = "Общественный транспорт",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4158),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4159),
                            Name = "Непродуктовые покупки",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4163),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4164),
                            Name = "Услуги",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4167),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4168),
                            Name = "Кредиты",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4172),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4173),
                            Name = "Прочие расходы",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4177),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4178),
                            Name = "Зарплата",
                            TransactionType = "Income"
                        },
                        new
                        {
                            Id = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4181),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4182),
                            Name = "Доход от аренды",
                            TransactionType = "Income"
                        },
                        new
                        {
                            Id = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4186),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4187),
                            Name = "Прочие даходы",
                            TransactionType = "Income"
                        },
                        new
                        {
                            Id = new Guid("80427d6d-6adb-49cc-8073-d113efaa4591"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4190),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 0, DateTimeKind.Local).AddTicks(4191),
                            Name = "Путешествия",
                            TransactionType = "Cunsumption"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TransactionSubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2d324f3-6b82-4a58-8e03-b75dc72a5a51"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9458),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9470),
                            Name = "Топливо"
                        },
                        new
                        {
                            Id = new Guid("a2a55fb6-4eff-4b71-a6d4-ccd37d029059"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9491),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9492),
                            Name = "Мойка"
                        },
                        new
                        {
                            Id = new Guid("7be33f4e-01e4-405b-8980-7002fe413392"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9496),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9497),
                            Name = "Ремонт"
                        },
                        new
                        {
                            Id = new Guid("9f37a9b3-c97d-4242-8f5c-81876f25ace3"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9518),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9519),
                            Name = "Обслуживание"
                        },
                        new
                        {
                            Id = new Guid("2fe4204d-b5ba-46de-a74f-86731c95c1a3"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9522),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9523),
                            Name = "Страховка"
                        },
                        new
                        {
                            Id = new Guid("f88125e9-72f9-4727-99e6-ebff669b6e08"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9530),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9531),
                            Name = "Стоянка"
                        },
                        new
                        {
                            Id = new Guid("bc4803b5-63dc-4fbb-b870-512ef114ee8f"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9535),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9536),
                            Name = "Штраф"
                        },
                        new
                        {
                            Id = new Guid("90701628-eb40-4e31-afbc-21f5e37a9cd8"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9539),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9540),
                            Name = "Телефон"
                        },
                        new
                        {
                            Id = new Guid("2a71fc0c-af77-459b-b75e-d3999f3f78dd"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9543),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9544),
                            Name = "Интернет"
                        },
                        new
                        {
                            Id = new Guid("c4c4a59b-c662-49a3-b8c6-2e107cf77447"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9548),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9549),
                            Name = "Коммунальные услуги"
                        },
                        new
                        {
                            Id = new Guid("a3b08375-941f-43fa-90d1-1eda2be9072a"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9552),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9553),
                            Name = "Электроенергия"
                        },
                        new
                        {
                            Id = new Guid("320459c2-ccf7-4393-a3bb-3f6412e93b5f"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9559),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9560),
                            Name = "Ресторан"
                        },
                        new
                        {
                            Id = new Guid("63a4deee-ff2c-4b22-81c0-e34bc7c4e88e"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9563),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9564),
                            Name = "Кинатеатр"
                        },
                        new
                        {
                            Id = new Guid("1ddf27c9-171b-4fc7-82e0-78cec3138949"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9567),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9568),
                            Name = "Аттракцион"
                        },
                        new
                        {
                            Id = new Guid("cd756a0d-e982-40c8-beb6-70d457f6fe2a"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9571),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9572),
                            Name = "Лекарство"
                        },
                        new
                        {
                            Id = new Guid("d6361978-6e63-4f33-b92d-b93672c8962e"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9575),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9576),
                            Name = "Услуги медцентров"
                        },
                        new
                        {
                            Id = new Guid("0c2f4ac7-1411-492a-913a-3a5177dc5c24"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9580),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9581),
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("c1297919-73f6-448d-a128-987269b306dd"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9585),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9586),
                            Name = "Алкоголь"
                        },
                        new
                        {
                            Id = new Guid("5197af3c-3aba-4552-961c-d6781e08a9f3"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9589),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9590),
                            Name = "Сладости"
                        },
                        new
                        {
                            Id = new Guid("6df7b7df-39d6-4b2e-8c29-506cad41388a"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9595),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9596),
                            Name = "Общественный транспорт"
                        },
                        new
                        {
                            Id = new Guid("f99470c6-4f9a-485b-9858-0ee2732e7af7"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9599),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9600),
                            Name = "Такси"
                        },
                        new
                        {
                            Id = new Guid("fc8057e7-3c62-47b5-8c03-1f84c3c1d611"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9603),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9604),
                            Name = "Химия"
                        },
                        new
                        {
                            Id = new Guid("aa8b7339-1845-4e94-a51e-dfb5ff9badc2"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9607),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9608),
                            Name = "Косметика"
                        },
                        new
                        {
                            Id = new Guid("89af454a-7032-4fd4-a340-9039b845fd65"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9611),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9612),
                            Name = "Алик"
                        },
                        new
                        {
                            Id = new Guid("f4b8abb6-30d1-480d-a547-0cd29bced68e"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9615),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9616),
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("c04735c6-51be-4190-b4af-839c9e56d023"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9619),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9620),
                            Name = "Стрижка"
                        },
                        new
                        {
                            Id = new Guid("ef709e74-a689-4afa-a3a5-a8c91d3d7819"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9623),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9624),
                            Name = "Маникюр"
                        },
                        new
                        {
                            Id = new Guid("f6a6379d-9560-4f0c-8888-6244fe050bf9"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9628),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9629),
                            Name = "Салон красоты"
                        },
                        new
                        {
                            Id = new Guid("86a2e66b-b4a2-4462-af08-ee6d54e68639"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9632),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9633),
                            Name = "Кредит на авто"
                        },
                        new
                        {
                            Id = new Guid("b3e8e60a-9e5f-4aeb-8a0b-3ae3debfc18e"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9636),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9637),
                            Name = "Кредит на ПК"
                        },
                        new
                        {
                            Id = new Guid("ee794fa1-9322-45e2-b110-7ede7abbebf1"),
                            CategoryId = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9640),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9641),
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("dc442900-cd3b-47fe-8528-3e7bb8ec8f4d"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9644),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9645),
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("bc2374e9-d51a-495a-abc2-59f778c25ec7"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9648),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9650),
                            Name = "Аванс"
                        },
                        new
                        {
                            Id = new Guid("ae981c5a-b6a5-4326-8ec1-4f474691e8ee"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9654),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9655),
                            Name = "Премия"
                        },
                        new
                        {
                            Id = new Guid("c4b5dd41-6fdb-4239-b8e5-639ac1913820"),
                            CategoryId = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9703),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9704),
                            Name = "Аренда квартиры"
                        },
                        new
                        {
                            Id = new Guid("d8de02c9-af8b-457f-853e-599a4be3e091"),
                            CategoryId = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9709),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9710),
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("fd8d2326-6e30-42a9-80ec-1d2f841e2026"),
                            CategoryId = new Guid("80427d6d-6adb-49cc-8073-d113efaa4591"),
                            CreatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9713),
                            LastUpdatedDate = new DateTime(2021, 6, 5, 19, 27, 14, 2, DateTimeKind.Local).AddTicks(9714),
                            Name = "ЕГИПЕТ(6/6/21 - 20/6/21)"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.BudgetDbModel", "Budget")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.AccountDbModel", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.BudgetDbModel", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
