// <auto-generated />
using System;
using FinanceManager.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManager.Persistence.Migrations
{
    [DbContext(typeof(FinanceManagerContext))]
    [Migration("20210419131345_add-user-id-to-transaction-model")]
    partial class adduseridtotransactionmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccauntSum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.BudgetDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 213, DateTimeKind.Local).AddTicks(5124),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4180),
                            Name = "Автомобиль",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4710),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4714),
                            Name = "Регулярные платежи",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4718),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4719),
                            Name = "Развлечения",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4722),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4723),
                            Name = "Медицина",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4726),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4727),
                            Name = "Продукты питания",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4732),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4733),
                            Name = "Общественный транспорт",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4736),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4737),
                            Name = "Непродуктовые покупки",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4740),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4741),
                            Name = "Услуги",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4744),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4745),
                            Name = "Кредиты",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4748),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4749),
                            Name = "Прочие расходы",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4752),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4753),
                            Name = "Зарплата",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4756),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4757),
                            Name = "Доход от аренды",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4760),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 214, DateTimeKind.Local).AddTicks(4761),
                            Name = "Прочие даходы",
                            TransactionType = 1
                        });
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TransactionSubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5842cbf7-ae3d-4a5e-b70b-50d03914f3e6"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8667),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8674),
                            Name = "Топливо"
                        },
                        new
                        {
                            Id = new Guid("a84bee18-1277-43ab-868c-8a342cb3e2d1"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8694),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8695),
                            Name = "Мойка"
                        },
                        new
                        {
                            Id = new Guid("a202a6b3-0134-4304-a3cc-43849ec28a12"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8699),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8700),
                            Name = "Ремонт"
                        },
                        new
                        {
                            Id = new Guid("978211ff-f365-48b4-9b62-3984da3f9935"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8718),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8719),
                            Name = "Обслуживание"
                        },
                        new
                        {
                            Id = new Guid("b62f580e-8960-4073-b35f-9265de29be2d"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8723),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8724),
                            Name = "Страховка"
                        },
                        new
                        {
                            Id = new Guid("98af9b7c-d9f3-44bb-ae11-25cf2a6be724"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8730),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8731),
                            Name = "Стоянка"
                        },
                        new
                        {
                            Id = new Guid("800d1352-b6aa-4941-953d-99b49b7931d6"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8734),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8735),
                            Name = "Штраф"
                        },
                        new
                        {
                            Id = new Guid("d5d1ce82-9a0c-4484-a2e8-1053129bdd25"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8738),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8739),
                            Name = "Телефон"
                        },
                        new
                        {
                            Id = new Guid("7d6f3a3a-c66e-46e4-9e2a-6cd9ecbaa634"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8742),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8743),
                            Name = "Интернет"
                        },
                        new
                        {
                            Id = new Guid("70e25033-49f0-4e5d-ad95-a182d656e3b5"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8747),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8748),
                            Name = "Коммунальные услуги"
                        },
                        new
                        {
                            Id = new Guid("6ddb293a-4e2d-4ddf-a051-b833f745b893"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8751),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8752),
                            Name = "Электроенергия"
                        },
                        new
                        {
                            Id = new Guid("1b2457c7-fdbc-4b39-aa6b-c1aa89d62906"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8758),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8759),
                            Name = "Ресторан"
                        },
                        new
                        {
                            Id = new Guid("9f8df247-8def-4e06-b6b3-2e4038092222"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8763),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8764),
                            Name = "Кинатеатр"
                        },
                        new
                        {
                            Id = new Guid("2c8ef699-874f-4a0b-94d6-9f3b03bb30d5"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8767),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8768),
                            Name = "Аттракцион"
                        },
                        new
                        {
                            Id = new Guid("1a4cabc6-b7b5-47a9-a9ec-e359d73d0038"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8771),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8772),
                            Name = "Лекарство"
                        },
                        new
                        {
                            Id = new Guid("8f55370c-64a8-48f8-901d-9351c34be713"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8818),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8819),
                            Name = "Услуги медцентров"
                        },
                        new
                        {
                            Id = new Guid("1e7f161e-759d-44a8-a371-081ecaa2c5be"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8823),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8824),
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("6d22c18a-efda-4fa3-a12c-4f0ae1367887"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8828),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8829),
                            Name = "Алкоголь"
                        },
                        new
                        {
                            Id = new Guid("76f722a6-6fe8-43ed-92e0-69d7f818b305"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8832),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8833),
                            Name = "Сладости"
                        },
                        new
                        {
                            Id = new Guid("69da084a-a3b0-4bd9-b4ee-682413fb2fd2"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8838),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8839),
                            Name = "Общественный транспорт"
                        },
                        new
                        {
                            Id = new Guid("fcf23d67-599d-4e24-978b-26ec5929a183"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8842),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8843),
                            Name = "Такси"
                        },
                        new
                        {
                            Id = new Guid("7efdab61-5d7e-45c3-b9f5-c76b7e51059b"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8846),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8847),
                            Name = "Химия"
                        },
                        new
                        {
                            Id = new Guid("d880fe06-d77c-47be-9c9f-847adac24261"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8850),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8851),
                            Name = "Косметика"
                        },
                        new
                        {
                            Id = new Guid("19d292e7-0a59-4dd8-b1fe-e6c1818d3421"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8855),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8856),
                            Name = "Алик"
                        },
                        new
                        {
                            Id = new Guid("aafd7c03-6045-487a-bedb-83eab5175aa6"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8859),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8860),
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("064a7bdf-0577-4780-9c65-720aa045f431"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8863),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8864),
                            Name = "Стрижка"
                        },
                        new
                        {
                            Id = new Guid("9ca31caf-06a3-40ae-85ab-65496ab26e47"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8867),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8868),
                            Name = "Маникюр"
                        },
                        new
                        {
                            Id = new Guid("f9311a0c-a98b-4334-8452-0d0564f9224b"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8873),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8874),
                            Name = "Салон красоты"
                        },
                        new
                        {
                            Id = new Guid("241b3046-e4d0-46a4-9916-e7d1e46b79f2"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8877),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8878),
                            Name = "Кредит на авто"
                        },
                        new
                        {
                            Id = new Guid("513c018f-8bb5-467c-b972-6e52d34ad0a3"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8881),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8882),
                            Name = "Кредит на ПК"
                        },
                        new
                        {
                            Id = new Guid("2d5ce2ad-1871-4a23-9649-607aa53ed101"),
                            CategoryId = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8885),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8886),
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("bb20360f-0390-43df-a528-83eb0635509f"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8889),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8890),
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("8e13f6fb-ec6c-4bec-9e39-e9fbeff7a1d3"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8893),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8894),
                            Name = "Аванс"
                        },
                        new
                        {
                            Id = new Guid("0ffa7866-69ca-47d9-a258-4a5d24b720e9"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8898),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8899),
                            Name = "Премия"
                        },
                        new
                        {
                            Id = new Guid("ca59d450-b84d-479e-b958-d7a14420666b"),
                            CategoryId = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8903),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8904),
                            Name = "Аренда квартиры"
                        },
                        new
                        {
                            Id = new Guid("04d1dfb7-caff-43ab-bdc4-0d9243c88538"),
                            CategoryId = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8908),
                            LastUpdatedDate = new DateTime(2021, 4, 19, 16, 13, 45, 216, DateTimeKind.Local).AddTicks(8909),
                            Name = "Подарки"
                        });
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.BudgetDbModel", "Budget")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.AccountDbModel", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Common.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.BudgetDbModel", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
