// <auto-generated />
using System;
using FinanceManager.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManager.Persistence.Migrations
{
    [DbContext(typeof(FinanceManagerContext))]
    partial class FinanceManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccauntSum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.BudgetDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 538, DateTimeKind.Local).AddTicks(370),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 538, DateTimeKind.Local).AddTicks(9665),
                            Name = "Автомобиль",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(205),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(210),
                            Name = "Регулярные платежи",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(214),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(215),
                            Name = "Развлечения",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(218),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(219),
                            Name = "Медицина",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(222),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(223),
                            Name = "Продукты питания",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(229),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(230),
                            Name = "Общественный транспорт",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(233),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(234),
                            Name = "Непродуктовые покупки",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(237),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(238),
                            Name = "Услуги",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(241),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(242),
                            Name = "Кредиты",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(245),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(246),
                            Name = "Прочие расходы",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(249),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(250),
                            Name = "Зарплата",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(253),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(254),
                            Name = "Доход от аренды",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(257),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 539, DateTimeKind.Local).AddTicks(258),
                            Name = "Прочие даходы",
                            TransactionType = 1
                        });
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TransactionSubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c042f085-0144-4eed-8897-90cce7e452b8"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3915),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3925),
                            Name = "Топливо"
                        },
                        new
                        {
                            Id = new Guid("5570b7c1-025a-41d2-af45-8f05d74c9937"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3947),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3948),
                            Name = "Мойка"
                        },
                        new
                        {
                            Id = new Guid("3cb89582-c39b-408c-92c0-be1777ce6d00"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3952),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3953),
                            Name = "Ремонт"
                        },
                        new
                        {
                            Id = new Guid("d75b8dc4-49c0-4044-af37-ff39e0f1a873"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3973),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3974),
                            Name = "Обслуживание"
                        },
                        new
                        {
                            Id = new Guid("329d71de-cb1a-4891-8171-054facfad305"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3978),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3979),
                            Name = "Страховка"
                        },
                        new
                        {
                            Id = new Guid("2762fb88-5750-4dc6-afea-4e4933d188e4"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3985),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3986),
                            Name = "Стоянка"
                        },
                        new
                        {
                            Id = new Guid("5ddfed7c-9fe8-44cb-a6f5-d8a040095fe6"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3989),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3990),
                            Name = "Штраф"
                        },
                        new
                        {
                            Id = new Guid("147486db-2158-4bee-99da-c78be4a7fd3d"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3993),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3994),
                            Name = "Телефон"
                        },
                        new
                        {
                            Id = new Guid("33d2262c-ba49-454d-8998-108a59f6f7b7"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3997),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(3998),
                            Name = "Интернет"
                        },
                        new
                        {
                            Id = new Guid("102b9b4a-484c-46d9-aa56-588f98beaf34"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4002),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4003),
                            Name = "Коммунальные услуги"
                        },
                        new
                        {
                            Id = new Guid("3cae7563-c709-46f4-874e-0256cdf4c048"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4007),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4008),
                            Name = "Электроенергия"
                        },
                        new
                        {
                            Id = new Guid("736ff34c-b5ba-450c-8045-e5613c2c44a3"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4014),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4015),
                            Name = "Ресторан"
                        },
                        new
                        {
                            Id = new Guid("1731eaea-e46c-4bcb-aee7-1331117b6719"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4018),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4019),
                            Name = "Кинатеатр"
                        },
                        new
                        {
                            Id = new Guid("bebfebdb-d305-4352-a0d2-2aecb7cdd7a8"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4022),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4023),
                            Name = "Аттракцион"
                        },
                        new
                        {
                            Id = new Guid("751c0e0d-1e88-403e-a5cb-66d119514407"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4026),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4027),
                            Name = "Лекарство"
                        },
                        new
                        {
                            Id = new Guid("649a30d9-c548-46cf-9fff-30ee8dfb3e8a"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4030),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4031),
                            Name = "Услуги медцентров"
                        },
                        new
                        {
                            Id = new Guid("7d23b5c1-cf60-4326-9a3b-d6f0a6ee0064"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4035),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4036),
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("471fe170-2494-4627-b4bd-1cac0133f03f"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4040),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4041),
                            Name = "Алкоголь"
                        },
                        new
                        {
                            Id = new Guid("15d9a392-4b70-4461-9319-7b598b00573e"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4044),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4045),
                            Name = "Сладости"
                        },
                        new
                        {
                            Id = new Guid("f62459bd-04eb-4ad4-a709-fd70847c77fe"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4050),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4051),
                            Name = "Общественный транспорт"
                        },
                        new
                        {
                            Id = new Guid("ba12c310-6f45-47ed-a02e-b9c3d8aefffd"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4054),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4055),
                            Name = "Такси"
                        },
                        new
                        {
                            Id = new Guid("f34fc0fc-56f4-4f5c-bc9c-40a847d0f700"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4059),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4060),
                            Name = "Химия"
                        },
                        new
                        {
                            Id = new Guid("a0f2927b-c0c2-4040-8615-c95a204637d5"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4063),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4064),
                            Name = "Косметика"
                        },
                        new
                        {
                            Id = new Guid("74790522-d12e-4557-929f-e68edb507ffa"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4067),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4068),
                            Name = "Алик"
                        },
                        new
                        {
                            Id = new Guid("de94bd9f-0a37-47d4-a74c-fab623371e07"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4071),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4072),
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("05cc5aa4-fb5b-4644-b31b-034e620f69f3"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4075),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4076),
                            Name = "Стрижка"
                        },
                        new
                        {
                            Id = new Guid("c07bd8b5-de84-48f0-88b5-cc2174471416"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4079),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4080),
                            Name = "Маникюр"
                        },
                        new
                        {
                            Id = new Guid("a0e479c3-10bb-497f-bccb-a556d611840d"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4085),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4086),
                            Name = "Салон красоты"
                        },
                        new
                        {
                            Id = new Guid("441ae8ef-7173-4524-97f3-0b741eada82e"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4089),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4090),
                            Name = "Кредит на авто"
                        },
                        new
                        {
                            Id = new Guid("a81d13b8-79d5-47f0-9fb6-0a1f46cb8038"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4093),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4094),
                            Name = "Кредит на ПК"
                        },
                        new
                        {
                            Id = new Guid("97967a6c-d1b4-4ef9-8a76-030abe9b8836"),
                            CategoryId = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4097),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4098),
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("47cf5a14-7ff4-4bf6-a7f0-df1b04683b57"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4101),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4102),
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("0a5574f0-1f2c-49b6-945f-6cf173dd68c8"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4106),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4107),
                            Name = "Аванс"
                        },
                        new
                        {
                            Id = new Guid("ef216a2f-6aed-4e66-a6d3-da979697e6ad"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4111),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4112),
                            Name = "Премия"
                        },
                        new
                        {
                            Id = new Guid("c5abb7d9-5481-4be0-9c3d-051e6d909b4c"),
                            CategoryId = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4115),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4116),
                            Name = "Аренда квартиры"
                        },
                        new
                        {
                            Id = new Guid("1a803e96-3797-4802-a884-94f938f1cf2e"),
                            CategoryId = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4121),
                            LastUpdatedDate = new DateTime(2021, 4, 1, 17, 43, 42, 541, DateTimeKind.Local).AddTicks(4122),
                            Name = "Подарки"
                        });
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.BudgetDbModel", "Budget")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.AccountDbModel", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Common.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.HasOne("FinanceManager.Common.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.AccountDbModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.BudgetDbModel", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Common.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
