// <auto-generated />
using System;
using FinanceManager.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManager.Persistence.Migrations
{
    [DbContext(typeof(FinanceManagerContext))]
    partial class FinanceManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccauntSum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.BudgetDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 173, DateTimeKind.Local).AddTicks(4173),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3214),
                            Name = "Автомобиль",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3951),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3955),
                            Name = "Регулярные платежи",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3963),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3964),
                            Name = "Развлечения",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3968),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3969),
                            Name = "Медицина",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3972),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3973),
                            Name = "Продукты питания",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3980),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3981),
                            Name = "Общественный транспорт",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3984),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3985),
                            Name = "Непродуктовые покупки",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3988),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3989),
                            Name = "Услуги",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3992),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3993),
                            Name = "Кредиты",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3998),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(3999),
                            Name = "Прочие расходы",
                            TransactionType = "Cunsumption"
                        },
                        new
                        {
                            Id = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4002),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4003),
                            Name = "Зарплата",
                            TransactionType = "Income"
                        },
                        new
                        {
                            Id = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4006),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4007),
                            Name = "Доход от аренды",
                            TransactionType = "Income"
                        },
                        new
                        {
                            Id = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4011),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 174, DateTimeKind.Local).AddTicks(4012),
                            Name = "Прочие даходы",
                            TransactionType = "Income"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TransactionSubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad9beb04-c59c-47bb-96de-d3489a38cd6e"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8032),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8039),
                            Name = "Топливо"
                        },
                        new
                        {
                            Id = new Guid("24c0ea2f-9951-4500-884c-ecdc36c8c58e"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8061),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8062),
                            Name = "Мойка"
                        },
                        new
                        {
                            Id = new Guid("6fe8dae3-e9bf-4525-82c5-fb4626b5e537"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8066),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8067),
                            Name = "Ремонт"
                        },
                        new
                        {
                            Id = new Guid("a0d1a95a-1ea2-4147-9384-e79f74eef48b"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8070),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8071),
                            Name = "Обслуживание"
                        },
                        new
                        {
                            Id = new Guid("e105dff4-0690-4c8f-ad5b-d2f5edfb2e9a"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8074),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8075),
                            Name = "Страховка"
                        },
                        new
                        {
                            Id = new Guid("14740629-55c0-47c6-b9ef-8ac7090b3810"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8081),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8082),
                            Name = "Стоянка"
                        },
                        new
                        {
                            Id = new Guid("04e6e177-ba23-4704-b9e9-fdb08a01755b"),
                            CategoryId = new Guid("06bfcef7-ae70-4040-beb9-8ab96620030b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8086),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8087),
                            Name = "Штраф"
                        },
                        new
                        {
                            Id = new Guid("8043d2e9-9af5-4697-bbc9-b6715d6d3b19"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8090),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8091),
                            Name = "Телефон"
                        },
                        new
                        {
                            Id = new Guid("861d1410-2ebf-45f8-a316-931559f695c3"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8098),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8099),
                            Name = "Интернет"
                        },
                        new
                        {
                            Id = new Guid("b2f22745-2331-464e-902c-d90b8b4629b1"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8104),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8105),
                            Name = "Коммунальные услуги"
                        },
                        new
                        {
                            Id = new Guid("a056adab-b99b-4107-a3c9-bc3374dec0f5"),
                            CategoryId = new Guid("6169f354-c9f8-48ac-bf4e-eca2f2b2922b"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8108),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8109),
                            Name = "Электроенергия"
                        },
                        new
                        {
                            Id = new Guid("2765d026-6348-4070-a366-d2ce0b1892bd"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8112),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8113),
                            Name = "Ресторан"
                        },
                        new
                        {
                            Id = new Guid("fbc75496-fab5-4180-9a70-07186bc239ce"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8116),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8117),
                            Name = "Кинатеатр"
                        },
                        new
                        {
                            Id = new Guid("e89c12be-9140-4ec9-9184-15e6e111d135"),
                            CategoryId = new Guid("1c09b880-cc78-4a32-9c64-85010fcabf66"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8121),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8122),
                            Name = "Аттракцион"
                        },
                        new
                        {
                            Id = new Guid("61abcac3-d132-438f-a7e0-5dc934bfd4c1"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8125),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8126),
                            Name = "Лекарство"
                        },
                        new
                        {
                            Id = new Guid("d572a123-e0a9-4a3f-bb59-fa6ef86634f6"),
                            CategoryId = new Guid("fbde9320-81f0-495f-a9ba-35ed8e4922ce"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8129),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8130),
                            Name = "Услуги медцентров"
                        },
                        new
                        {
                            Id = new Guid("440fb9c4-98ce-47a8-b22e-15a9e95c6260"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8136),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8137),
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("73e8bb5d-945a-451c-b86e-18f40edd1592"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8141),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8142),
                            Name = "Алкоголь"
                        },
                        new
                        {
                            Id = new Guid("bbed3b29-70d4-4edc-a1b1-9342e5116ba9"),
                            CategoryId = new Guid("c1ce6959-3af6-410a-8427-9a173654da0d"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8145),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8146),
                            Name = "Сладости"
                        },
                        new
                        {
                            Id = new Guid("aec69ec6-befb-468a-b04a-9e54e25682f6"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8150),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8151),
                            Name = "Общественный транспорт"
                        },
                        new
                        {
                            Id = new Guid("74f2693f-4eb9-4fa1-984a-55755d89f2ca"),
                            CategoryId = new Guid("bcbdc4d2-3667-4b57-b2db-86bb5777d806"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8154),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8155),
                            Name = "Такси"
                        },
                        new
                        {
                            Id = new Guid("fb93ff2c-e66d-4503-a6b7-b0b754f446c9"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8158),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8159),
                            Name = "Химия"
                        },
                        new
                        {
                            Id = new Guid("37b43c2c-6a49-4002-8e7e-a6a2e7d7b9a6"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8162),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8163),
                            Name = "Косметика"
                        },
                        new
                        {
                            Id = new Guid("e47d5a0a-9211-422c-be9a-4333f7264a52"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8166),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8167),
                            Name = "Алик"
                        },
                        new
                        {
                            Id = new Guid("d30fff7b-7e81-48d0-ad38-b40db9e8a26f"),
                            CategoryId = new Guid("975b99ae-3b02-4fd1-9008-f9327b0e0538"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8172),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8173),
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("ff950d4d-5c6b-41a3-b5b5-bebb74cf54fc"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8176),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8177),
                            Name = "Стрижка"
                        },
                        new
                        {
                            Id = new Guid("cb5656f1-52f4-434d-a35b-f1557d9f08c5"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8180),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8181),
                            Name = "Маникюр"
                        },
                        new
                        {
                            Id = new Guid("75e7bf17-1351-451f-b9e0-4f7797afe760"),
                            CategoryId = new Guid("55f65fdb-59eb-4033-b4aa-9f7704b709f2"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8184),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8185),
                            Name = "Салон красоты"
                        },
                        new
                        {
                            Id = new Guid("3e0bc499-937b-4d6e-85c3-22e29792fe01"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8188),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8189),
                            Name = "Кредит на авто"
                        },
                        new
                        {
                            Id = new Guid("87fcdc88-d300-4a0b-9d1b-2bb91d4e4207"),
                            CategoryId = new Guid("9525e3cc-c1db-404b-960b-717c09297602"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8192),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8193),
                            Name = "Кредит на ПК"
                        },
                        new
                        {
                            Id = new Guid("5c9e3682-e7bb-49d1-ba1d-fad984b13584"),
                            CategoryId = new Guid("c468f57a-9771-4427-97ea-d174827803c7"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8197),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8198),
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("af997e88-c8ca-4054-8968-ef059206f1dd"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8201),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8202),
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("240b3253-0caa-4ef4-a13b-caf2ee8a3577"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8207),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8208),
                            Name = "Аванс"
                        },
                        new
                        {
                            Id = new Guid("f8517e33-73ec-458a-9087-e43fa447daab"),
                            CategoryId = new Guid("181336f7-1482-4c9f-9bff-f1cd186bf097"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8245),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8246),
                            Name = "Премия"
                        },
                        new
                        {
                            Id = new Guid("54864952-c568-4005-8884-fdad472ac488"),
                            CategoryId = new Guid("25d1f35e-fa4c-4026-8d5f-01f85491cd59"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8250),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8251),
                            Name = "Аренда квартиры"
                        },
                        new
                        {
                            Id = new Guid("08a7b02d-48a6-4154-97b1-b5a381fcc274"),
                            CategoryId = new Guid("20e41593-9451-4277-84ab-d10e8f9af04e"),
                            CreatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8254),
                            LastUpdatedDate = new DateTime(2021, 4, 24, 12, 59, 51, 176, DateTimeKind.Local).AddTicks(8255),
                            Name = "Подарки"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.BudgetDbModel", "Budget")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.AccountDbModel", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionSubCategoryDbModel", b =>
                {
                    b.HasOne("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.AccountDbModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.BudgetDbModel", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Domain.DbModels.TransactionCategoryDbModel", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
